name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Confirmation to deploy'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Confirm deployment
        if: github.event.inputs.confirmation == 'true'
        run: echo "Deployment confirmed."

      - name: Build Docker image
        run: docker build -t cloud-uploader .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag cloud-uploader ghcr.io/${{ github.repository_owner }}/cloud-uploader
          docker push ghcr.io/${{ github.repository_owner }}/cloud-uploader
